name: Build Geode Mod

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows
            os: windows-latest
            target: Win
          - name: macOS
            os: macos-latest
            target: Mac
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build mod
      uses: geode-sdk/build-geode-mod@main
      with:
        combine: true
